CasgemPortfolio/Controllers/PortfolioController.cs
using CasgemPortfolio.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CasgemPortfolio.Controllers
{
    public class PortfolioController : Controller
    {
        CasgemPortfolioDbEntities db = new CasgemPortfolioDbEntities();
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult PartialHead()
        {
            return PartialView();
        }
        public PartialViewResult PartialNavbar()
        {
            return PartialView();
        }
        public PartialViewResult PartialFeature()
        {
            ViewBag.featureTitle = db.TblFeature.Select(x => x.FeatureTitle).FirstOrDefault();
            ViewBag.featureDescription = db.TblFeature.Select(x => x.FeatureDescription).FirstOrDefault();
            ViewBag.featureImage = db.TblFeature.Select(x => x.FeatureImageUrl).FirstOrDefault();

            return PartialView();
        }
        public PartialViewResult PartialWhoIAm()
        {
            ViewBag.title = db.TblWhoAmI.Select(x => x.Title).FirstOrDefault();
            ViewBag.description = db.TblWhoAmI.Select(x => x.Description).FirstOrDefault();
            return PartialView();
        }
        public ActionResult Download()
        {
            ViewBag.cv = db.TblWhoAmI.Select(x => x.CvLink).FirstOrDefault();
            string filePath = Server.MapPath("~/Templates/" + ViewBag.cv);
            return File(filePath, "application/pdf", ViewBag.cv);
        }
        public PartialViewResult PartialMyResume()
        {
            var values = db.TblResume.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialService()
        {
            var values = db.TblService.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialStatistic()
        {
            ViewBag.totalService = db.TblService.Count();
            ViewBag.totalMessage = db.TblMessage.Count();
            ViewBag.totalThanksMessage = db.TblMessage.Where(x => x.MessageSubject == "Teşekkür").Count();
            ViewBag.happyCustomer = 12;
            return PartialView();
        }
        public PartialViewResult PartialTestimonials()
        {
            var values = db.TblTestimonial.ToList();
            return PartialView(values);
        }
        public PartialViewResult PartialVideo()
        {
            return PartialView();
        }
        public PartialViewResult PartialFooter()
        {
            return PartialView();
        }
        public PartialViewResult PartialScripts()
        {
            var textArray = db.TblSkill.Select(x => x.SkillName).ToArray();
            ViewBag.skillArray = textArray;
            return PartialView();
        }
    }
}

CasgemPortfolio/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Proje 2</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Ana Sayfa</a></li>
                <li><a href="#">Kişiler</a></li>
                <li><a href="#">Duyurular</a></li>
                <li><a href="#">Yardım</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>

</body>
</html>

CasgemPortfolio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CasgemPortfolio/Views/Shared/_PortfolioAdminLayout.cshtml
@{
    Layout = null;
}

<!doctype html>
<html lang="en">
<head>
    <title>Sidebar 01</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/Templates/sidebar-01/css/style.css">
</head>
<body>

    <div class="wrapper d-flex align-items-stretch">
        <nav id="sidebar">
            <div class="p-4 pt-5">
                <a href="#" class="img logo rounded-circle mb-5" style="background-image: url(https://avatars.githubusercontent.com/u/70902532?v=4);"></a>
                <ul class="list-unstyled components mb-5">
                    <li><a href="/Portfolio/Index">Ben Kimim</a></li>
                    <li><a href="~/Templates/Yusuf Eldemir-CV.pdf">Cv Açıklaması</a></li>
                    <li><a href="/Service/Index/">Hizmetlerim</a></li>
                    <li><a href="/Reference/Index/">Referanslarım</a></li>
                    <li><a href=https://github.com/yusufeldemirr>Projelerim</a></li>
                    <li><a href="/Contact/Index/">İletişim</a></li>
                    <li><a href="/Message/Index/">Mesajlar</a></li>
                </ul>

                <div class="footer">
                    <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright &copy;
                        <script>document.write(new Date().getFullYear());</script> Tüm hakları saklıdır.</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    </p>
                </div>

            </div>
        </nav>

        <!-- Page Content  -->
        <div id="content" class="p-4 p-md-5">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-primary">
                        <i class="fa fa-bars"></i>
                        <span class="sr-only">Toggle Menu</span>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fa fa-bars"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="/Portfolio/Index">Siteye Git</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="@Url.Action("Download", "Portfolio")">Cv'mi İndir</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="https://github.com/yusufeldemirr">Github</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="/Message/Index/">Mesajlar</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            @RenderBody()
        </div>
    </div>

    <script src="~/Templates/sidebar-01/js/jquery.min.js"></script>
    <script src="~/Templates/sidebar-01/js/popper.js"></script>
    <script src="~/Templates/sidebar-01/js/bootstrap.min.js"></script>
    <script src="~/Templates/sidebar-01/js/main.js"></script>
</body>
</html>